# -*- coding: utf-8 -*-
"""Healthcare_Patient_streamlit_ready.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eh5kprKEFq-QWoE2oG0HOLsRPINMZ6hD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
data = pd.read_excel("Healthcare_Patient_Records_3000.xlsx")

data.head()

print(data.shape)
print(data.info())
print(data.isnull().sum())

data['BMI_Category'] = pd.cut(
    data['BMI'],
    bins=[0,18.5,25,30,100],
    labels=[0,1,2,3]
)

data['Age_Group'] = pd.cut(
    data['Age'],
    bins=[0,30,50,100],
    labels=[0,1,2]
)

data['BMI_Category'] = data['BMI_Category'].astype(int)
data['Age_Group'] = data['Age_Group'].astype(int)

X = data.drop('Diabetes', axis=1)
y = data['Diabetes']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

accuracies = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    accuracies[name] = acc
    print(f"{name} Accuracy: {acc:.4f}")

plt.figure()
plt.bar(accuracies.keys(), accuracies.values())
plt.xticks(rotation=45)
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.show()

best_model_name = max(accuracies, key=accuracies.get)
print("Best Model:", best_model_name)

best_model = models[best_model_name]

y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))

new_patient = [[45, 1, 32, 90, 160, 120, 1, 1, 1, 3, 2]]

new_patient = scaler.transform(new_patient)

prediction = best_model.predict(new_patient)

if prediction[0] == 1:
    print("Patient is likely Diabetic")
else:
    print("Patient is Non-Diabetic")

from sklearn.metrics import confusion_matrix

# Predict
y_pred = best_model.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:\n", cm)

import matplotlib.pyplot as plt
import numpy as np

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.colorbar()

classes = ['Non-Diabetic', 'Diabetic']
tick_marks = np.arange(len(classes))
plt.xticks(tick_marks, classes)
plt.yticks(tick_marks, classes)

# Add numbers inside matrix
for i in range(len(classes)):
    for j in range(len(classes)):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center")

plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

accuracy = (cm[0,0] + cm[1,1]) / cm.sum()
print("Accuracy from Confusion Matrix:", accuracy)



"""
## Deployment Preparation (Streamlit + GitHub)

The following steps save the trained model and scaler so they can be used in a Streamlit web application.

1. Train the best model (Random Forest).
2. Save the model using joblib.
3. Use the saved model inside a Streamlit app for prediction.
"""

import joblib

# Train the best model again if needed
best_model = RandomForestClassifier()
best_model.fit(X_train, y_train)

# Save model and scaler
joblib.dump(best_model, "diabetes_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved successfully.")

"""
### Streamlit App Example (app.py)

Create a new file called **app.py** in your GitHub repository and paste the following code.
"""

!pip install streamlit -qq

import streamlit as st
import joblib
import numpy as np

# The previous try-except block for installation is no longer needed here
# as the installation command is now at the top.

model = joblib.load("diabetes_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Diabetes Prediction App")

age = st.number_input("Age")
gender = st.selectbox("Gender (0=Female,1=Male)",[0,1])
bmi = st.number_input("BMI")
bp = st.number_input("Blood Pressure")
glucose = st.number_input("Glucose Level")
insulin = st.number_input("Insulin Level")
activity = st.selectbox("Physical Activity (1-4)",[1,2,3,4])
family = st.selectbox("Family History (0/1)",[0,1])
smoking = st.selectbox("Smoking (0/1)",[0,1])

if st.button("Predict"):
    data = np.array([[age,gender,bmi,bp,glucose,insulin,activity,family,smoking]])
    data = scaler.transform(data)
    prediction = model.predict(data)

    if prediction[0] == 1:
        st.error("Patient likely diabetic")
    else:
        st.success("Patient likely non-diabetic")